config/routes.rb
MinhasReceitas::Application.routes.draw do
  
  resources :welcome, :only => [:index]

  namespace :admin do
    resources :recipes
    resources :categories, :except => [:show]
  end

  resources :recipes, :only => [:index, :show] do
    resources :comments
  end

  root :to => 'welcome#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :recipes

  validates_presence_of :name
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  
  attr_accessible :author, :body, :email, :recipe, :url

  belongs_to :recipe

  validates_presence_of :body, :recipe

  validates_associated :recipe

  with_options :allow_blank => true do |c|
		c.validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/
		c.validates_format_of :url,   :with => /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$/ix 
	end

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :description, :ingredients, :title, :category_id, :image, :grade, :preparation, :comments, :author_id

  belongs_to :category

  has_many :comments

  validates_presence_of :description, :ingredients, :title, :category_id, :grade, :preparation

  scope :published, lambda {
  	where(published_at < ?", false, Time.current)
  }
  scope :search, lambda { |terms| 
  	where("title LIKE :t OR ingredients LIKE :t OR preparation LIKE :t", :t => "%#{terms}%")
  }

end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  layout 'admin'
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end


  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])
    
    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_categories_path, notice: 'Category was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to edit_admin_category_path(@category), notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to admin_categories_path }
      format.json { head :no_content }
    end
  end
end

app/controllers/admin/recipes_controller.rb
class Admin::RecipesController < Admin::AdminController
  
  before_filter :load_resources, :only => %w(new create edit update)

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recipes }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.json
  def new
    @recipe = Recipe.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(params[:recipe])

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to admin_recipes_path, notice: 'Recipe was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.json
  def update
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to admin_recipes_path, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to admin_recipes_url }
      format.json { head :no_content }
    end
  end

  protected
  def load_resources
    @categories = Category.all
    @authors = []
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  # def create
  #   @recipe = Recipe.find (params[:recipe_id])
  #   unless @recipe.comments.create(params[:comment])
  #  	  redirect_to @recipe, flash[:alert] = 'Fail to receive the comment. Double check the fields.'
  #   else
  #   	redirect_to @recipe
  #   end
  # end
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @comment = @recipe.comments.build(params[:comment])
    flash[:alert] = 'Fail to receive the comment. Double check the fields' unless @comment.save 

    redirect_to @recipe
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_filter :load_categories

  # GET /recipes
  # GET /recipes.json
  def index

    if params[:search].present?
      @recipes = Recipe.search(params[:search])
    else
      @recipes = Recipe.all
    end

    # @recipes = Recipe.scoped
    
    # @recipes = @category.recipes if @category.present?
    # @recipes = @recipes.published

    

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recipes }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    # @recipe = Recipe.published.find(params[:id])
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recipe }
    end
  end

protected
  def load_categories
    @categories = Category.all
    @category   = Category.find(params[:category_id]) if params[:category_id]
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
 	
	end
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper

  def link_to_new(model, url, html_options = {})
    link_to t("new", :model => model.model_name.human), url, html_options
  end

  def link_to_edit(url, html_options = {})
    html_options.reverse_merge!(:class => "green")
    link_to t("edit"), url, html_options
  end

  def link_to_destroy(url, html_options = {})
    html_options.reverse_merge!(:confirm => 'Quer mesmo apagar?', :method => :delete, :class => "red")
    link_to t("destroy"), url, html_options  end

  def section(title="", &block)
    content_tag :div, :class => "section" do
      html = ""
      html  = content_tag :h3, title if title.present?
      html  = content_tag :div, :class => "in", &block
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def flash_messages
      flash.collect do |key, msg|
        content_tag(:p, msg, :id => key, :class => "flash_message")
      end.join.html_safe
    end
	
	def error_messages_for(resource)
	  render "shared/error_messages", :resource => resource
	end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper

	def gravatar_image_tag(email, html_options = {})
		email = Digest::MD5.hexdigest(email)
		image_tag "http://www.gravatar.com/avatar/#{email}?size=48", html_options
	end

	def comment_author(name, url="")
		name = "Anonymous Coward" unless name.present?
		url.present? ? link_to(name, url, :target => "_blank") : name
	end
	
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <%= error_messages_for @category %>

  <div class="field">
    <%= f.text_field :name, :placeholder => "Nome da Categoria" %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-success btn-small" %> <%= link_to "cancel", admin_categories_path, :class => "btn btn-danger btn-small" %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h2><%= t"admin.category.edit.title" %></h2>
</br>
<%= render 'form' %>

app/views/admin/categories/index.html.erb
<div class='row'>
  <div class='span12'>
    <div class='well'>
      
      <h2><%= t"admin.category.index.name" %></h2>

      <% if @categories.present? %>
      <ul class="list">
        <% @categories.each do |category| %>
          <h3><%= category.name %></h3>

          <p>
            <%= link_to_edit [:edit, :admin, category], :class => "btn btn-info btn-mini" %>
            <%= link_to_destroy [:admin, category], :class => "btn btn-danger btn-mini" %>
          </p>
        <% end %>
      </ul>
      <% else %>
        <p>A categoria ainda não está incluida.</p>
      <% end %>
 
    </div>
  </div>
</div>
<p>
  <%= link_to t(:new_category), new_admin_category_path, :class => "btn btn-success btn-small" %>
</p> 

app/views/admin/categories/new.html.erb
<h2><%= t"admin.category.new.title" %></h2>
</br>
<%= render 'form' %>

app/views/admin/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= t "activerecord.attributes.category.name" %></b>
  <%= @category.name %>
</p>


<%= link_to t(:edit), edit_category_path(@category) %> |
<%= link_to t(:back), categories_path %>

app/views/admin/recipes/_form.html.erb
<%= form_for [:admin, @recipe] do |f| %>
  <%= error_messages_for @recipe %>

  <div class="field">
    <%= f.label :author_id, "Receita de: " %>
    <%= f.collection_select :author_id, @authors, :id, :full_name %>
  </div>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, :placeholder => "Nome da Receita", :class => "title" %>
  </div>

  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>

  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>

  <div class="field">
    <%= f.label :grade %><br />
    <%= f.select :grade, options_for_select([[ "Nota 10", 10 ], ["Nota 9", 9], ["Nota 8", 8], ["Nota 7", 7], ["Nota 6", 6], ["Nota 5", 5], ["Nota 4", 4], ["Nota 3", 3], ["Nota 2", 2], ["Nota 1", 1], ["Nota 0", 0]]) %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :cols => 100, :rows => 10 %>
  </div>

  <div class="field">
    <%= f.label :ingredients %><br />
    <%= f.text_area :ingredients, :cols => 100, :rows => 10 %>
  </div>

  <div class="field">
    <%= f.label :preparation %><br />
    <%= f.text_area :preparation, :cols => 100, :rows => 10 %>
  </div>

  <div class="actions">
    <%= f.submit "Salvar", :class => "btn btn-success btn-small" %>     
    <%= link_to t(:back), admin_recipes_path, :class => "btn btn-primary btn-small" %>
  </div>
<% end %>

app/views/admin/recipes/edit.html.erb
<h2><%= t"recipe.edit.title" %></h2>

<%= render 'form' %>

app/views/admin/recipes/index.html.erb
<div class='row'>
  <div class='span12'>
    <div class='well'>

      <h2><%= t"recipe.index.title" %></h2>
      <br/>
      <% if @recipes.present? %>
      <ul class="list">
        <% @recipes.each do |recipe| %>
          <h3>
            <%= link_to recipe.title.titleize, admin_recipe_path(recipe) %> | 
            <%= recipe.category.name %>
          </h3>
          
          <p>
            <%= link_to_edit [:edit, :admin, recipe], :class => "btn btn-info btn-mini" %>
            <%= link_to_destroy [:admin, recipe], :class => "btn btn-danger btn-mini" %>
          </p>
        <% end %>
      </ul>
      <% else %>
        <p>Teremos novas receitas em breve.</p>
      <% end %>
    </div>
  </div>
</div>
<p>
  <%= link_to t(:new_recipe), new_admin_recipe_path, :class => "btn btn-success btn-small" %>
</p>

app/views/admin/recipes/new.html.erb
<h2><%= t"recipe.new.title" %></h2>

<%= render 'form' %>

app/views/admin/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="span8">
		<h2><%= @recipe.title.titleize %></h2>

		<h3>em <%= @recipe.category.name %></h3>

		<h3>Nota <%= @recipe.grade %></h3>
		
		<hr/>

		<h4>Sobre a receita</h4>
		<p><%= simple_format @recipe.description %></p>

		<h4>Ingredientes</h4>
		<div class="ingredientes">
			<%= simple_format @recipe.ingredients %>
		</div>
		
		<h4>Modo de preparo</h4>
		<p><%= simple_format @recipe.preparation %></p>

		<hr/>
		<%= link_to t(:edit), edit_admin_recipe_path(@recipe), :class => "btn btn-info btn-mini" %> <%= link_to t(:back), admin_recipes_path, :class => "btn btn-primary btn-mini" %>
	</div>

	<div class="span4">
		<%= image_tag @recipe.image %>
		<br/>
		<br/>
		<br/>
		<h3>Comentários</h3>
		<div id="comments">
		<%- if @recipe.comments.any? -%>
		  <%= render :partial => "comments/comment", :collection => @recipe.comments %>
		<%- else -%>
		  <p>Essa receita não tem comentários</p>
		<%- end -%>
		</div>
	</div>
</div>

app/views/comments/_comment.html.erb
<%= div_for comment do %>
	<br/>
  <div class="author">
    <div class="avatar"><%= gravatar_image_tag comment.email %></div>
    <div class="meta">
      <h4 class="name"><%= comment_author(comment.author, comment.url) %></h4>
      <i class="date">há <%= time_ago_in_words comment.created_at %></i>
    </div>
  </div>

  <div class="body" style="margin-bottom:20px;">
    <%= comment.body %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [ recipe, comment ] do |f| %>
  
  <%= error_messages_for comment %>
  <hr>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body, :rows => 10, :cols => 90 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</hr>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t :title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="padding-top: 60px;">

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to t(:title), root_path, :class => "brand"%>
        <ul class='nav'>
          <li><%= link_to "Receitas", recipes_path %></li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown">
                Admin
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Categorias - Admin", admin_categories_path %></li>
              <li><%= link_to "Receitas - Admin", admin_recipes_path %></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <div class='container'>

    <div id="content-wrapper">
      <div id="content">
        <div class="in">
          <%= flash_messages %>
          <%= yield %>
        </div>
      </div>
    </div>
  <br/>
  <p>Criado por Cristine Mari Aguilar</p>
  
  </div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t :title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="padding-top: 60px;">

	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
	      <div class="container">
	      	<%= link_to t(:title), root_path, :class => "brand"%>
			<ul class='nav'>
				<li><%= link_to "Receitas", recipes_path %></li>
				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown">
					    Admin
					    <b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li><%= link_to "Categorias - Admin", admin_categories_path %></li>
						<li><%= link_to "Receitas - Admin", admin_recipes_path %></li>
					</ul>
				</li>
			</ul>
			
			<%= form_tag recipes_path, :method => :get, :class => "navbar-search pull-right" do %>
			    <%= text_field_tag :search, "",
			          :placeholder => "Busca de Receitas",
			          :type => "search",
			          :class => "search-query" %>
			    <button type="submit" class="btn-primary btn-mini">Buscar</button>
			<% end %>
			
	      </div>
		</div>
	</div>

	<div class='container'>

		<div class='row'>
			<div class='span12'>
				<%= yield %>
			</div>
		</div>

	<p>Criado por Cristine Mari Aguilar</p>

	<%= flash_messages %>
	
	</div>

</body>
</html>

app/views/recipes/index.html.erb
<h1><%= t"recipe.index.title" %></h1>
<div class='row'>
  <div class='span12'>
    <div class='well'>
    <%- if @recipes.present? -%>

      <% @recipes.each do |recipe| %>
        <hr>
        <h2><%= link_to recipe.title.titleize, recipe %></h2>
        <h3><%= recipe.category.name %></h3>

        <div id="recipe">
          <p>
            <%= simple_format excerpt(recipe.description, "", 50) %> 
            <%= link_to "continue ...", recipe, :class => "btn btn-info btn-mini" %>
          </p>       
        </div>
        </hr>
      <% end %>

    <% else %>
      <p>Teremos novas receitas em breve.</p>
    <% end %>

    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="span8">

		<h2><%= @recipe.title.titleize %></h2>

		<h3>em <%= @recipe.category.name %></h3>

		<h3>Nota <%= @recipe.grade %></h3>
		
		<hr/>

		<h4>Sobre a receita</h4>
		<p><%= simple_format @recipe.description %></p>

		<h4>Ingredientes</h4>
		<div class="ingredientes">
			<%= simple_format @recipe.ingredients %>
		</div>
		
		<h4>Modo de preparo</h4>
		<p><%= simple_format @recipe.preparation %></p>

		<hr/>
		<%= link_to t(:back), recipes_path, :class => "btn btn-primary btn-mini" %>
	</div>

	<div class="span4">
		<%= image_tag @recipe.image %>
		<br/>
		<br/>
		<br/>
		<h3>Comentários</h3>
		<div id="comments">
		<%- if @recipe.comments.any? -%>
		  <%= render :partial => @recipe.comments %>
		<%- else -%>
		  <p>Nobody commented this recipe yet.</p>
		<%- end -%>
		</div>
		<%= render "comments/form", :recipe => @recipe, :comment => Comment.new %>
	</div>
</div>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(resource.errors.count, "error") %> prohibited this <%= resource.class.model_name.human %> from being saved:</h2>

    <ul>
    <% resource.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/welcome/_searchbar.html.erb
<div id="column2">

  <h3>Busca de receitas</h3>

  <%= form_tag recipes_path, :method => :get do %>
    <%= text_field_tag :search, "",
      :placeholder => "Ingrediente ou Receita",
      :size => 30,
      :type => "text",
      :class => "input-medium search-query" %>      
  	<button type="submit" class="btn">Buscar</button>
  <% end %>


</div>

app/views/welcome/index.html.erb
<%= stylesheet_link_tag "application", :media => "all" %>
  
<div id="content">
	<div id="column1">
		<h3>Minhas Receitas</h3>
		<p>Icing gummi bears pastry pudding I love. I love pastry icing pie lemon drops. Icing cupcake icing. Gummi bears fruitcake oat cake. Apple pie wafer soufflé brownie pie chocolate cake. Lemon drops halvah jelly-o wypas sweet bonbon brownie. Halvah bear claw powder wypas gummies jelly beans brownie soufflé.</p>
		<p>Sesame snaps macaroon liquorice candy brownie tart bonbon toffee. Carrot cake powder topping. Wafer brownie chupa chups bonbon danish. Marzipan liquorice powder cake wafer chocolate jujubes. Lollipop I love I love lollipop carrot cake. Pie gummi bears I love cotton candy gummies lemon drops. Ice cream biscuit cupcake caramels. Gingerbread caramels biscuit tiramisu. I love pudding gingerbread carrot cake donut brownie danish fruitcake.</p>
	</div>
	<div id="column2">
		<h3>Participe</h3>
		<p>Lollipop jujubes pastry wypas lemon drops tootsie roll. Gummi bears powder sesame snaps macaroon pastry sweet. I love chocolate bonbon tiramisu tart oat cake pastry. </p>
		<p>Lemon drops marshmallow chocolate I love. Faworki soufflé brownie lemon drops cupcake. Pastry danish chocolate cake marshmallow jelly beans croissant liquorice. Biscuit dragée cotton candy cupcake. Dragée macaroon I love apple pie wypas I love croissant sweet roll. I love icing chocolate wypas I love I love cake oat cake biscuit. Faworki apple pie I love marzipan chocolate I love marshmallow.</p>
	</div>
	<%= render "searchbar" %>
</div>